INSERT INTO TIPOANOMALIA VALUES(000,'NN');
INSERT INTO TIPOPRODUCTO VALUES(000,'NN');
INSERT INTO TIPOSOLICITUD VALUES(000,'NN');
INSERT INTO FUNCIONARIO VALUES('000','NN',NULL,'NN','NN');
INSERT INTO PRODUCTO VALUES(000,NULL,000);  

CREATE TABLE retorno (
    retorno     VARCHAR2(400 CHAR) );
